### ISSUE TITLE
onshape-to-robot

### ISSUE THREAD

**Issue by dioufbb** [Rhoban/onshape-to-robot#120]
hello i'm tryna to create a my robot urdf but i have as output this 
Traceback (most recent call last):
  File "/usr/local/bin/onshape-to-robot", line 8, in <module>
    sys.exit(onshape_to_robot.main())
  File "/usr/local/lib/python3.10/dist-packages/onshape_to_robot/onshape_to_robot.py", line 246, in main
    buildRobot(tree, np.matrix(np.identity(4)))
  File "/usr/local/lib/python3.10/dist-packages/onshape_to_robot/onshape_to_robot.py", line 206, in buildRobot
    addPart(occurrence, matrix)
  File "/usr/local/lib/python3.10/dist-packages/onshape_to_robot/onshape_to_robot.py", line 91, in addPart
    with open(config['outputDirectory']+'/'+stlFile, 'wb') as stream:
PermissionError: [Errno 13] Permission denied: 'AGV_Project/part_1.stl'
Someone can help me

**Comment by Gregwar** [comment]
Hello,

From the error message, it looks like you don't have permissions to write a STL file in the output directory

**Comment by dioufbb** [comment]
and i remark something during the onshape to robot installation; i didnt acheive the clonage  step ; it doesn't work; did you think it can affect my work
I get something like that
VirtualBox:~$ git clone git@github.com:Rhoban/onshape-to-robot.git
Cloning into 'onshape-to-robot'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
