### ISSUE TITLE
Pulling from Branches

### ISSUE THREAD

**Issue by ThomasPiechulek** [Rhoban/onshape-to-robot#47]
Hello,
i can not find a possibility to onshape-to-robot on a specified branch. The script seems to just take the last one active.
Can you add the Workspace Id in the Config.json to solve this ?

**Comment by Gregwar** [comment]
Hello,
Can you use `versionId` parameter for that ?
https://onshape-to-robot.readthedocs.io/en/latest/config.html#versionid

**Comment by Gregwar** [comment]
Currently, `versionId` can be used to specify a version (`/v/`), I can also add a `workspaceId` to be used `/w/` if you need it

**Comment by ThomasPiechulek** [comment]
Hello,
yes that would be great.
Beacause we try to do everything automatically, and with the version id, we have to manually create versions every time...
Thank you so much.
________________________________
Von: Grégoire Passault <notifications@github.com>
Gesendet: Donnerstag, 25. Februar 2021 13:23
An: Rhoban/onshape-to-robot <onshape-to-robot@noreply.github.com>
Cc: Thomas Piechulek <thomas.piechulek@isento.de>; Author <author@noreply.github.com>
Betreff: Re: [Rhoban/onshape-to-robot] Pulling from Branches (#47)


Currently, versionId can be used to specify a version (/v/), I can also add a workspaceId to be used /w/ if you need it

**Comment by Gregwar** [comment]
Just added `workspaceId` configuration entry, can you confirm it's working for you ?

**Comment by ThomasPiechulek** [comment]
works fine, thank you.
________________________________
Von: Grégoire Passault <notifications@github.com>
Gesendet: Freitag, 26. Februar 2021 13:24
An: Rhoban/onshape-to-robot <onshape-to-robot@noreply.github.com>
Cc: Thomas Piechulek <thomas.piechulek@isento.de>; Author <author@noreply.github.com>
Betreff: Re: [Rhoban/onshape-to-robot] Pulling from Branches (#47)


Just added workspaceId configuration entry, can you confirm it's working for you ?

**Comment by ThomasPiechulek** [comment]
In the code we are searching for the ID, but it wants to print the Keyword Workspace, so some kollegues have this error occuring.
Strangely this Eroor does not appear for me so sorry for the early confirm.

Traceback (most recent call last):
  File ".../bin/onshape-to-robot", line 3, in <module>
    from onshape_to_robot import onshape_to_robot
  File "...lib/python3.8/site-packages/onshape_to_robot/onshape_to_robot.py", line 14, in <module>
    from .load_robot import \
  File ".../lib/python3.8/site-packages/onshape_to_robot/load_robot.py", line 19, in <module>
    config['workspace']+' ...' + Style.RESET_ALL)
KeyError: 'workspace'

**Comment by isetre** [comment]
The problem seems to be in the load_robot.py file at ll. 18 ff., where the config is accessed with a faulty key and later on the workspaceId variable is required. The code snippet below contains my edits with which the code worked.
`workspaceId=config['workspaceId']
print("\n" + Style.BRIGHT + '* Using configuration workspace ID ' +
          config['workspaceId']+' ...' + Style.RESET_ALL)`
By the way, great work you're doing here!

**Comment by Gregwar** [comment]
You are right, sorry
Should be fixed in `v0.3.9`

**Comment by isetre** [comment]
works fine now, thanks
