### ISSUE TITLE
Root [occurrences]; KeyError

### ISSUE THREAD

**Issue by ECP68** [Rhoban/onshape-to-robot#62]
I'm trying to download the cad into urdf. It seems like there is no occurrences from onshape.

* Retrieving assembly "Assembly 10" with id d5ee290fc2a98e8ecce43ea0
Traceback (most recent call last):
  File "/home/xxxxxxx/.local/bin/onshape-to-robot", line 3, in <module>
    from onshape_to_robot import onshape_to_robot
  File "/home/xxxxxxx/.local/lib/python3.8/site-packages/onshape_to_robot/onshape_to_robot.py", line 14, in <module>
    from .load_robot import \
  File "/home/xxxxxxx/.local/lib/python3.8/site-packages/onshape_to_robot/load_robot.py", line 94, in <module>
    for occurrence in root['occurrences']:
KeyError: 'occurrences'

Can it be a problem with the CAD?

Thanks

**Comment by Gregwar** [comment]
Sorry for the delay, did you manage to solve your problem ?
