### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by andrestoga** [Rhoban/onshape-to-robot#90]
I'm getting the following traceback error by only exporting a part I imported to OnShape in parasolid format:
```

Traceback (most recent call last):
  File "/home/andrestoga/python_venv/onshape_ros/bin/onshape-to-robot", line 11, in <module>
    sys.exit(onshape_to_robot.main())
  File "/home/andrestoga/python_venv/onshape_ros/lib/python3.6/site-packages/onshape_to_robot/onshape_to_robot.py", line 239, in main
    buildRobot(tree, np.matrix(np.identity(4)))
  File "/home/andrestoga/python_venv/onshape_ros/lib/python3.6/site-packages/onshape_to_robot/onshape_to_robot.py", line 203, in buildRobot
    addPart(occurrence, matrix)
  File "/home/andrestoga/python_venv/onshape_ros/lib/python3.6/site-packages/onshape_to_robot/onshape_to_robot.py", line 141, in addPart
    mass = massProperties['mass'][0]
IndexError: list index out of range
```

Any idea of what's happening?

@Gregwar I can dm you an example so you can reproduce the error I'm having if you want

**Comment by Gregwar** [comment]
I will close this as it is very old
Do not hesitate to re-open and provide an Onshape assembly reproducing your issue if you believe there is still seomthing to fix
